#!/usr/bin/env python3
"""Interactive chat-style generation for a saved GPT-2 checkpoint."""
import argparse
import re
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM


def clean_assistant_reply(full_text: str, prompt: str) -> str:
    reply = full_text[len(prompt):]
    # Stop at common delimiters generated by the model.
    for sep in ["<|endoftext|>", "\nUser:", "\nSystem:"]:
        pos = reply.find(sep)
        if pos >= 0:
            reply = reply[:pos]
    # If it repeats Assistant:, keep text after the first generated marker.
    reply = re.sub(r"^\s*Assistant:\s*", "", reply)
    return reply.strip()


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--model-dir", type=str, required=True)
    parser.add_argument("--system-prompt", type=str, default="You are a helpful assistant.")
    parser.add_argument("--max-new-tokens", type=int, default=120)
    parser.add_argument("--temperature", type=float, default=0.8)
    parser.add_argument("--top-p", type=float, default=0.9)
    parser.add_argument("--repetition-penalty", type=float, default=1.12)
    parser.add_argument("--history-turns", type=int, default=4)
    parser.add_argument("--device", type=str, default="cuda" if torch.cuda.is_available() else "cpu")
    args = parser.parse_args()

    tokenizer = AutoTokenizer.from_pretrained(args.model_dir, use_fast=True)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token
    model = AutoModelForCausalLM.from_pretrained(args.model_dir).to(args.device)
    model.eval()

    history = []
    print("Loaded model:", args.model_dir)
    print("Type 'exit' or 'quit' to stop.\n")

    while True:
        user = input("You: ").strip()
        if user.lower() in {"exit", "quit", "q"}:
            break
        if not user:
            continue

        recent = history[-args.history_turns:]
        prompt_parts = []
        if args.system_prompt:
            prompt_parts.append(f"System: {args.system_prompt}")
        for u, a in recent:
            prompt_parts.append(f"User: {u}")
            prompt_parts.append(f"Assistant: {a}")
        prompt_parts.append(f"User: {user}")
        prompt_parts.append("Assistant:")
        prompt = "\n".join(prompt_parts)

        inputs = tokenizer(prompt, return_tensors="pt", truncation=True, max_length=768).to(args.device)
        with torch.no_grad():
            out = model.generate(
                **inputs,
                max_new_tokens=args.max_new_tokens,
                do_sample=True,
                temperature=args.temperature,
                top_p=args.top_p,
                repetition_penalty=args.repetition_penalty,
                pad_token_id=tokenizer.eos_token_id,
                eos_token_id=tokenizer.eos_token_id,
            )
        full_text = tokenizer.decode(out[0], skip_special_tokens=False)
        reply = clean_assistant_reply(full_text, prompt)
        if not reply:
            reply = "[empty reply]"
        print(f"GPT-2: {reply}\n")
        history.append((user, reply))


if __name__ == "__main__":
    main()
